### ISSUE TITLE
retryOrExit is calling process.exit with a boolean (false)

### ISSUE THREAD

**Issue by sakher** [tirsen/retry-cli#9]
Seems there is a case where you guys are calling process.exit with a boolean.

lerna ERR! yarn run dev exited 1 in '@xxxxxxxxxxx-path'
lerna ERR! yarn run dev stdout:
/var/run/xxxxxxx:xxxxxx - accepting connections
lerna ERR! yarn run dev stderr:
 Container xxxxxxxxxxx-container  Running
node:internal/validators:95
      throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type boolean (false)
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at retryOrExit (file:///Users/xxxxxxxx/code/xxxxxx/xxxxxxxxxxxxx.yarn/cache/retry-cli-npm-0.7.0-xxxxxxxx.zip/node_modules/retry-cli/cli.js:48:15)
    at ChildProcess.<anonymous> (file:///xxxxxxxxxxxxxx/.yarn/cache/retry-cli-npm-0.7.0-xxxxx-xxxx.zip/node_modules/retry-cli/cli.js:53:5)
    at ChildProcess.emit (node:events:512:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by alfaproject** [comment]
Just got hit by this as well when updating to node 20

**Comment by vdineva** [comment]
+1
When can we expect this to be fixed? It's also blocking us from upgrading to node 20
